version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-java"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n1oaqmnoyaba"
s3_prefix = "cloud-resume-java"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
